# ENUNCIADO MINI-PROYECTO FINAL
# ENTREGA: DICIEMBRE 6 DE 2023
# Talento TICs 2023
# Python Avanzado (Python con librerías de análisis de datos)

# PYTHON Y ANÁLISIS DE DATOS: 
# (A) MODULO/SCRIPT EN PYTHON PARA CARGA/PROCESAMIENTO/ANALISIS Y VISUALIZACIÓN DE
#     COMPORTAMIENTO DE DATASETS
# (B) PRESENTACIÓN FINAL

# MENU DE OPCIONES:
# 1. CARGAR DATASET - SELECCIONAR UNO DE DOS DATASETS ELEGIDOS POR CADA UNO, 
#                     UNO DE LOS CUALES DEBE CONTENER AL MENOS UNA SERIE DE TIEMPO                     
# 2. REALIZAR LIMPIEZA DEL DATASET (realizar la limpieza del dataset,)
#                           mostrar mensaje de retroalimentación al usuario 
#                     2.1 GUARDAR DATASET LIMPIO
# 3. REALIZAR TAREAS DE ANÁLISIS BÁSICAS DEL DATASET:
#                     3.1 MOSTRAR PARÁMETROS ESTADÍSTICOS DEL DATASET
#                     3.2 MOSTRAR MATRIZ DE CORRELACIÓN
#                     3.3 REALIZAR OPERACIONES DE AGRUPAMIENTO Y AGREGACIÓN
#                     3.4 PARA EL DATASET CON SERIE DE TIEMPO, GENERAR DEBIDAMENTE
#                         LA TABLA PIVOTE
# 4. MOSTRAR AL MENOS 4 TIPOS DE GRÁFICOS, QUE EL USUARIO ELIJA (OFRECERLE OPCIONES)



